export const bgSlides = [
  {
    titleSrc: "",
    link: "",
    imgSrc: {
      large: "main-1-xl.png",
      medium: "main-1-m.png",
      small: "main-1-s.png",
    },
    bgColor: "linear-gradient(90deg, #00213D 0%, #020308 100%)",
    titleHeight: "34%",
    color: "black",
    content: ["OFFICIAL", "MV AGUSTA", "MERCHANDISE"],
  },
  {
    titleSrc: "",
    link: "",
    imgSrc: {
      large: "main-2-xl.png",
      medium: "main-2-m.png",
      small: "main-2-s.png",
    },
    bgColor: "linear-gradient(90deg, #00213D 0%, #020308 100%)",
    titleHeight: "34%",
    color: "black",
    content: ["OFFICIAL", "MV AGUSTA", "MERCHANDISE"],
  },
];
export const HeaderData = [
  {
    price: "17.490",
    nameHeaderTitle: "f3-800/f3-800.svg",
    bgHeaderParallax_Large: "header/main-banner-1-1_desk.png",
    bgHeaderParallax_Small: "header/main-banner-1-1_mobile.png",
    manifesto_Arr: ["OFFICIAL", "MV AGUSTA", "MERCHANDISE"],
    bg: "#f4bf3b",
    colorBg: "linear-gradient(104.42deg, #9e7000 .69%, #f4bf3b 98.81%)",
    contentHeaderContent:
      "",
    titleSize: "auto 16%",
    reveredContent: true,
    heightContentTop: "22%",
    position: "absolute",
    posRight: "40px",
    transformMedia: "none",
    // width: "100%",
    posBottom: "0",
    imgHeight: "80%",
  },
  {
    price: "17.490",
    nameHeaderTitle: "f3-800/f3-800.svg",
    bgHeaderParallax_Large: "header/main-banner-2-1_desk.png",
    bgHeaderParallax_Small: "header/main-banner-2-1_mobile.png",
    manifesto_Arr: ["OFFICIAL", "MV AGUSTA", "MERCHANDISE"],
    bg: "#8b96a0",
    colorBg: "linear-gradient(99.34deg, #25272a 4.5%, #8b96a0 94.95%)",
    contentHeaderContent:
      "",
    titleSize: "auto 16%",
    reveredContent: true,
    heightContentTop: "22%",
    position: "absolute",
    posRight: "40px",
    transformMedia: "none",
    // width: "100%",
    posBottom: "0",
    imgHeight: "80%",
  },
];
